Repository ChrisO345/furthermaths-module, pull requests merged in 2022-10, with the labels that each got.

#3 Added Manhattan Distance
  furthermaths/distance.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#5 Fixed binomial distribution
  furthermaths/distributions/binomial.py
Labels: optimisations

#11 Added Angle between vectors
  furthermaths/vectors/__init__.py
  furthermaths/vectors/angle.py
Labels: hacktoberfest, optimisations, hacktoberfest-accepted

#18 Added surface_area_ellipsoid and surface_area_paraboloid
  furthermaths/surface_area.py
  furthermaths/volume.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 added simple interest formula
  furthermaths/financial/__init__.py
  furthermaths/financial/simple_interest.py
Labels: hacktoberfest, hacktoberfest-accepted

#17 feat: added co-ordinate geometry
  furthermaths/coordinate_geometry.py
Labels: hacktoberfest, hacktoberfest-accepted, new feature

#21 updated fibonacci function
  furthermaths/series/fibbonacci.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#20 added compound interest formula
  furthermaths/financial/__init__.py
  furthermaths/financial/compound_interest.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added volume of paraboloid
  furthermaths/volume.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Add Triangular Number
  furthermaths/series/triangular_number.py
Labels: hacktoberfest, hacktoberfest-accepted, new feature

#25 Added more functions and clear description in arithmetic module
  furthermaths/series/arithmetic.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#4 New Surface Area formula
  furthermaths/surface_area.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
